project:
  type: website
  output-dir: docs

website:
  title: "David K. Amakye"
  site-url: "https://RealKingDavid.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts/
    right:
      - icon: github
        href: "https://github.com/RealKingDavid"

format:
  html:
    theme: default
    css: resources/styles.css
    toc: true
